[client]
showSidebarNavigation = false

[theme]
primaryColor="#e04f07"
backgroundColor="#ffffff"
secondaryBackgroundColor="#d2defa"
textColor="#0a2461"
font="sans serif"


# Primary accent for interactive elements
    #primaryColor = '#7792E3'

# Background color for the main content area
#backgroundColor = '#fffff'

# Background color for sidebar and most interactive widgets
    #secondaryBackgroundColor = '#e4ebed'

# Color used for almost all text
    #textColor = '#042669'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
#font = "sans serif"
